---
###########################################################
#   6- web server config
###########################################################

#
# - name: "Enable mod-wsgi in Apache"
#   command: "a2enmod wsgi"
#   notify:
#     - "Restart Apache"

# - name: "Remove default Apache server sites"
#   command: "a2dissite {{ item }}"
#   with_items:
#     - "000-default"
#     - "default"
#   notify:
#     - "Restart Apache"
#   ignore_errors: yes
# # note that yes in ignore_errors must be without quotes (ansible bug?)
#
# - name: "Template dashboard apache2 config"
#   template:
#     src: "etc_apache2_sites_dashboard.conf.j2"
#     dest: "/etc/apache2/sites-available/dashboard.conf"

# - name: "Enable apache dashboard site"
#   command: "a2ensite dashboard"
#   args:
#     creates: "/etc/apache2/sites-enabled/dashboard.conf"
#   notify:
#     - "Restart Apache"

- name: "Template dashboard apache2 config"
  template:
    src: "etc_httpd_confd_dashboard.conf.centos.j2"
    dest: "/etc/httpd/conf.d/dashboard.conf"

# - name: "Enable services"
#   service:
#     name: "{{ item }}"
#     state: "restarted"
#     enabled: "yes"
#   with_items:
#     - "elasticsearch"
#     - "archivematica-mcp-server"
#     - "archivematica-mcp-client"
#     - "apache2"

- name: "Enable and start gearmand"
  service:
    name: "gearmand"
    state: "started"
    enabled: "yes"

- name: "Enable and (Re)start MCP Server, MCP Client, httpd"
  service:
    name: "{{ item }}"
    state: "restarted"
    enabled: "yes"
  with_items:
    - "archivematica-mcp-server"
    - "archivematica-mcp-client"
    - "httpd"
